# Copyright (c) 2025, ETH Zurich (Robotic Systems Lab)
# Author: Pascal Roth
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

import os

import isaaclab.terrains as terrain_gen

import nav_tasks.terrains as fdm_terrain_gen

from fdm import FDM_DATA_DIR

from .terrains import RslStairsCfg

BASELINE_2D_TERRAIN_CFG = terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=1.0,
    border_height=2.0,
    num_rows=6,
    num_cols=6,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    curriculum=False,
    sub_terrains={
        "flat": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=1.0,
            noise_range=(0.0, 0.005),
            noise_step=0.005,
            border_width=0.25,
            vertical_scale=0.001,
        ),
        "easy_ramp": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_ramp_slope=True,
            ramp_slope_range=(8, 15),
            step_width=0.3,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.2,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.4,
        ),
        "easy_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "medium_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.6, 1.0],
            proportion=0.5,
        ),
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[0.8, 1.2],
            proportion=0.5,
            wall_width=0.15,
        ),
    },
)
FDM_TERRAINS_CFG= terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=1.0,
    border_height=2.0,
    num_rows=6,
    num_cols=6,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    curriculum=False,
    sub_terrains={
        "flat": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=1.0,
            noise_range=(0.0, 0.005),
            noise_step=0.005,
            border_width=0.25,
            vertical_scale=0.001,
        ),
        "easy_ramp": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_ramp_slope=True,
            ramp_slope_range=(8, 15),
            step_width=0.3,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.2,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.4,
        ),
        "easy_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "medium_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.6, 1.0],
            proportion=0.5,
        ),
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[0.8, 1.2],
            proportion=0.5,
            wall_width=0.15,
        ),
    },
)
FDM_EVAL_EXTEROCEPTIVE_TERRAINS_CFG= terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=1.0,
    border_height=2.0,
    num_rows=6,
    num_cols=6,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    curriculum=False,
    sub_terrains={
        "flat": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=1.0,
            noise_range=(0.0, 0.005),
            noise_step=0.005,
            border_width=0.25,
            vertical_scale=0.001,
        ),
        "easy_ramp": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_ramp_slope=True,
            ramp_slope_range=(8, 15),
            step_width=0.3,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.2,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.4,
        ),
        "easy_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "medium_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.6, 1.0],
            proportion=0.5,
        ),
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[0.8, 1.2],
            proportion=0.5,
            wall_width=0.15,
        ),
    },
)
FDM_EXTEROCEPTIVE_TERRAINS_CFG=terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=1.0,
    border_height=2.0,
    num_rows=6,
    num_cols=6,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    curriculum=False,
    sub_terrains={
        "flat": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=1.0,
            noise_range=(0.0, 0.005),
            noise_step=0.005,
            border_width=0.25,
            vertical_scale=0.001,
        ),
        "easy_ramp": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_ramp_slope=True,
            ramp_slope_range=(8, 15),
            step_width=0.3,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.2,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.4,
        ),
        "easy_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "medium_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.6, 1.0],
            proportion=0.5,
        ),
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[0.8, 1.2],
            proportion=0.5,
            wall_width=0.15,
        ),
    },
)
FDM_ROUGH_TERRAINS_CFG=terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=1.0,
    border_height=2.0,
    num_rows=6,
    num_cols=6,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    curriculum=False,
    sub_terrains={
        "flat": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=1.0,
            noise_range=(0.0, 0.005),
            noise_step=0.005,
            border_width=0.25,
            vertical_scale=0.001,
        ),
        "easy_ramp": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_ramp_slope=True,
            ramp_slope_range=(8, 15),
            step_width=0.3,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.2,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.4,
        ),
        "easy_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "medium_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.6, 1.0],
            proportion=0.5,
        ),
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[0.8, 1.2],
            proportion=0.5,
            wall_width=0.15,
        ),
    },
)
PLANNER_EVAL_CFG= terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=2.0,
    num_rows=15,
    num_cols=20,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        # 主力：稍微加密一点的 pillar
        "outdoor": fdm_terrain_gen.MeshPillarTerrainCfg(
            proportion=0.45,
            box_objects=fdm_terrain_gen.MeshPillarTerrainCfg.BoxCfg(
                width=(0.35, 0.9),
                length=(0.2, 0.45),
                max_yx_angle=(0, 10),
                height=(2.5, 2.5),
                num_objects=(2, 3),
            ),
            cylinder_cfg=fdm_terrain_gen.MeshPillarTerrainCfg.CylinderCfg(
                radius=(0.25, 0.45),
                max_yx_angle=(0, 5),
                height=(2.5, 2.5),
                num_objects=(2, 3),
            ),
        ),

        # 单个 box
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[1.0, 1.8],
            proportion=0.22,
        ),

        # 单个 cylinder
        "single_cylinder": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="cylinder",
            dim_range=[0.5, 0.9],
            proportion=0.13,
        ),

        # 少量 wall，但别太多
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[1.0, 1.6],
            proportion=0.01,
        ),

        # 少量 cross pattern，增加转向避障
        "box_cross_pattern": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.5, 0.9],
            position_pattern=fdm_terrain_gen.cross_object_pattern,
            proportion=0.07,
        ),

        # 极少量宽松 maze，作为 harder sample
        "maze": fdm_terrain_gen.RandomMazeTerrainCfg(
            proportion=0.01,
            resolution=2.0,
            maze_height=3.0,
            step_height_range=(0.08, 0.12),
            step_width_range=(0.35, 0.45),
            num_stairs=0,
        ),
    },
)
PLANNER_EVAL_CFG= terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=2.0,
    num_rows=15,
    num_cols=20,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        # 主力：稍微加密一点的 pillar
        "outdoor": fdm_terrain_gen.MeshPillarTerrainCfg(
            proportion=0.45,
            box_objects=fdm_terrain_gen.MeshPillarTerrainCfg.BoxCfg(
                width=(0.35, 0.9),
                length=(0.2, 0.45),
                max_yx_angle=(0, 10),
                height=(2.5, 2.5),
                num_objects=(1, 2),
            ),
            cylinder_cfg=fdm_terrain_gen.MeshPillarTerrainCfg.CylinderCfg(
                radius=(0.25, 0.45),
                max_yx_angle=(0, 5),
                height=(2.5, 2.5),
                num_objects=(1, 2),
            ),
        ),

        # 单个 box
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[1.0, 1.8],
            proportion=0.22,
        ),

        # 单个 cylinder
        "single_cylinder": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="cylinder",
            dim_range=[0.5, 0.9],
            proportion=0.13,
        ),

        # 少量 wall，但别太多
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[1.0, 1.6],
            proportion=0.01,
        ),

        # 少量 cross pattern，增加转向避障
        "box_cross_pattern": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.5, 0.9],
            position_pattern=fdm_terrain_gen.cross_object_pattern,
            proportion=0.07,
        ),

        # 极少量宽松 maze，作为 harder sample
        "maze": fdm_terrain_gen.RandomMazeTerrainCfg(
            proportion=0.01,
            resolution=2.0,
            maze_height=3.0,
            step_height_range=(0.08, 0.12),
            step_width_range=(0.35, 0.45),
            num_stairs=0,
        ),
    },
)
PLANNER_EVAL_2D_CFG= terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=2.0,
    num_rows=15,
    num_cols=20,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    sub_terrains={
        # 主力：稍微加密一点的 pillar
        "outdoor": fdm_terrain_gen.MeshPillarTerrainCfg(
            proportion=0.45,
            box_objects=fdm_terrain_gen.MeshPillarTerrainCfg.BoxCfg(
                width=(0.35, 0.9),
                length=(0.2, 0.45),
                max_yx_angle=(0, 10),
                height=(2.5, 2.5),
                num_objects=(2, 3),
            ),
            cylinder_cfg=fdm_terrain_gen.MeshPillarTerrainCfg.CylinderCfg(
                radius=(0.25, 0.45),
                max_yx_angle=(0, 5),
                height=(2.5, 2.5),
                num_objects=(2, 3),
            ),
        ),

        # 单个 box
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[1.0, 1.8],
            proportion=0.22,
        ),

        # 单个 cylinder
        "single_cylinder": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="cylinder",
            dim_range=[0.5, 0.9],
            proportion=0.13,
        ),

        # 少量 wall，但别太多
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[1.0, 1.6],
            proportion=0.01,
        ),

        # 少量 cross pattern，增加转向避障
        "box_cross_pattern": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.5, 0.9],
            position_pattern=fdm_terrain_gen.cross_object_pattern,
            proportion=0.07,
        ),

        # 极少量宽松 maze，作为 harder sample
        "maze": fdm_terrain_gen.RandomMazeTerrainCfg(
            proportion=0.01,
            resolution=2.0,
            maze_height=3.0,
            step_height_range=(0.08, 0.12),
            step_width_range=(0.35, 0.45),
            num_stairs=0,
        ),
    },
)
PAPER_FIGURE_TERRAIN_CFG=terrain_gen.TerrainGeneratorCfg(
    size=(10.0, 10.0),
    border_width=1.0,
    border_height=2.0,
    num_rows=6,
    num_cols=6,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    slope_threshold=0.75,
    use_cache=False,
    curriculum=False,
    sub_terrains={
        "flat": terrain_gen.HfRandomUniformTerrainCfg(
            proportion=1.0,
            noise_range=(0.0, 0.005),
            noise_step=0.005,
            border_width=0.25,
            vertical_scale=0.001,
        ),
        "easy_ramp": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_ramp_slope=True,
            ramp_slope_range=(8, 15),
            step_width=0.3,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.2,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.4,
        ),
        "easy_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "medium_stairs": fdm_terrain_gen.StairsRampEvalTerrainCfg(
            proportion=1.0,
            modify_step_height=True,
            step_height_range=(0.06, 0.10),
            step_width=0.35,
            platform_width=1.5,
            center_platform_width=1.5,
            border_width=0.25,
            width_randomization=0.0,
            random_stairs_ramp_position_flipping=False,
            free_space_front=True,
            no_free_space_front=False,
            random_wall_probability=0.0,
            all_wall=False,
            max_height=0.3,
        ),
        "single_box": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="box",
            dim_range=[0.6, 1.0],
            proportion=0.5,
        ),
        "single_wall": fdm_terrain_gen.SingleObjectTerrainCfg(
            object_type="wall",
            dim_range=[0.8, 1.2],
            proportion=0.5,
            wall_width=0.15,
        ),
    },
)