# Copyright (c) 2025, ETH Zurich (Robotic Systems Lab)
# Author: Pascal Roth
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

from __future__ import annotations

from isaaclab.utils import configclass

from .command_ratio_curriculum import RandomPlannerCommandRatioCurriculum


@configclass
class RandomPlannerCommandRatioCurriculumCfg:
    """Configuration for the curriculum to increase the commands generated by the planner."""

    class_type: type = RandomPlannerCommandRatioCurriculum

    command_term_name: str = "command"
    """The name of the command term in the MDP configuration."""

    start_ratio: float = 0.0
    """The initial ratio of planner commands."""
    end_ratio: float = 1.0
    """The final ratio of planner commands."""
    update_step: float = 0.1
    """The step size to increase the ratio."""

    update_interval: int = 10000
    """The number of reset environments before the ratio is updated."""
