# Copyright (c) 2025, ETH Zurich (Robotic Systems Lab)
# Author: Pascal Roth
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Forward Dynamics Model specific randomization utilities."""

from __future__ import annotations

import math
import numpy as np
import torch
from typing import TYPE_CHECKING

from isaaclab.assets import Articulation, RigidObject
from isaaclab.managers import SceneEntityCfg
from isaaclab.utils.math import quat_apply_yaw, quat_from_euler_xyz, sample_uniform

from nav_tasks.mdp import FixGoalCommand, GoalCommand

from ..commands import MixedCommand

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedEnv, ManagerBasedRLEnv


def randomize_rigid_body_material_uniform_static_dynamic_friction(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    static_friction_range: tuple[float, float],
    dynamic_friction_range: tuple[float, float],
    restitution_range: tuple[float, float],
    num_buckets: int,
    asset_cfg: SceneEntityCfg,
    regular: bool = False,
):
    """Randomize the physics materials on all geometries of the asset.

    ..note ::
        Change to original function is that static friction is set to be equal to dynamic friction

    This function creates a set of physics materials with random static friction, dynamic friction, and restitution
    values. The number of materials is specified by ``num_buckets``. The materials are generated by sampling
    uniform random values from the given ranges.

    The material properties are then assigned to the geometries of the asset. The assignment is done by
    creating a random integer tensor of shape  (num_instances, max_num_shapes) where ``num_instances``
    is the number of assets spawned and ``max_num_shapes`` is the maximum number of shapes in the asset (over
    all bodies). The integer values are used as indices to select the material properties from the
    material buckets.

    .. attention::
        This function uses CPU tensors to assign the material properties. It is recommended to use this function
        only during the initialization of the environment. Otherwise, it may lead to a significant performance
        overhead.

    .. note::
        PhysX only allows 64000 unique physics materials in the scene. If the number of materials exceeds this
        limit, the simulation will crash.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]

    if not isinstance(asset, (RigidObject, Articulation)):
        raise ValueError(
            f"Randomization term 'randomize_rigid_body_material' not supported for asset: '{asset_cfg.name}'"
            f" with type: '{type(asset)}'."
        )

    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device="cpu")
    else:
        env_ids = env_ids.cpu()

    # retrieve material buffer
    materials = asset.root_physx_view.get_material_properties()
    # sample material properties from the given ranges
    material_samples = np.zeros(materials[env_ids].shape)

    if regular and (static_friction_range[1] - static_friction_range[0]) != 0.0:
        material_samples[..., 0] = np.arange(
            static_friction_range[0],
            static_friction_range[1],
            step=(static_friction_range[1] - static_friction_range[0]) / env.num_envs,
        )[:, None]
    else:
        material_samples[..., 0] = np.random.uniform(*static_friction_range, size=(env.num_envs, 1))

    material_samples[..., 1] = material_samples[..., 0].copy()
    # material_samples[..., 1] = np.random.uniform(*dynamic_friction_range)
    material_samples[..., 2] = np.random.uniform(*restitution_range, size=(env.num_envs, 1))

    # create uniform range tensor for bucketing
    lo = np.array([static_friction_range[0], static_friction_range[0], restitution_range[0]])
    # lo = np.array([static_friction_range[0], dynamic_friction_range[0], restitution_range[0]])
    hi = np.array([static_friction_range[1], static_friction_range[1], restitution_range[1]])
    # hi = np.array([static_friction_range[1], dynamic_friction_range[1], restitution_range[1]])

    # to avoid 64k material limit in physx, we bucket materials by binning randomized material properties
    # into buckets based on the number of buckets specified
    for d in range(3):
        buckets = np.array([(hi[d] - lo[d]) * i / num_buckets + lo[d] for i in range(num_buckets)])
        material_samples[..., d] = buckets[
            np.clip(np.searchsorted(buckets, material_samples[..., d]), 0, num_buckets - 1)
        ]

    # update material buffer with new samples
    if isinstance(asset, Articulation) and asset_cfg.body_ids != slice(None):
        # obtain number of shapes per body (needed for indexing the material properties correctly)
        # note: this is a workaround since the Articulation does not provide a direct way to obtain the number of shapes
        #  per body. We use the physics simulation view to obtain the number of shapes per body.
        num_shapes_per_body = []
        for link_path in asset.root_physx_view.link_paths[0]:
            link_physx_view = asset._physics_sim_view.create_rigid_body_view(link_path)  # type: ignore
            num_shapes_per_body.append(link_physx_view.max_shapes)

        # sample material properties from the given ranges
        for body_id in asset_cfg.body_ids:
            # start index of shape
            start_idx = sum(num_shapes_per_body[:body_id])
            # end index of shape
            end_idx = start_idx + num_shapes_per_body[body_id]
            # assign the new materials
            # material ids are of shape: num_env_ids x num_shapes
            # material_buckets are of shape: num_buckets x 3
            materials[env_ids, start_idx:end_idx] = torch.from_numpy(material_samples[:, start_idx:end_idx]).to(
                dtype=torch.float
            )
    else:
        materials[env_ids] = torch.from_numpy(material_samples).to(dtype=torch.float)

    # apply to simulation
    asset.root_physx_view.set_material_properties(materials, env_ids)


def reset_root_state_center(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the asset root state to zero velocity, forward orientation and a linearly spaced position."""

    asset: Articulation = env.scene[asset_cfg.name]
    root_states = asset.data.default_root_state[env_ids].clone()
    origins = env.scene.env_origins[env_ids]

    # positions: near env origin, tiny xy perturbation only
    positions = root_states[:, :3].clone()
    positions[:, :2] = origins[:, :2]
    positions[:, 2] = origins[:, 2] + 0.80

    # optional tiny xy noise
    xy_noise = sample_uniform(-0.05, 0.05, (len(env_ids), 2), device=asset.device)
    positions[:, :2] += xy_noise

    # yaw: keep very small for humanoid stability
    safe_yaw_min = -0.01
    safe_yaw_max = 0.01
    yaw_samples = sample_uniform(safe_yaw_min, safe_yaw_max, (len(env_ids), 1), device=asset.device)
    orientations = quat_from_euler_xyz(
        torch.zeros_like(yaw_samples),
        torch.zeros_like(yaw_samples),
        yaw_samples,
    ).squeeze(1)

    # zero root velocity
    velocities = torch.zeros((len(env_ids), 6), device=asset.device)

    # write root
    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)

    # default joints, zero joint velocity
    default_joint_pos = asset.data.default_joint_pos[env_ids].clone()
    default_joint_vel = torch.zeros_like(asset.data.default_joint_vel[env_ids])
    asset.write_joint_state_to_sim(default_joint_pos, default_joint_vel, env_ids=env_ids)

def reset_root_state_paper_plot(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """
    Ultra-stable humanoid reset:
    - keep default root orientation
    - place robot at env origin with fixed safe z
    - zero root velocity
    """

    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    root_states = asset.data.default_root_state[env_ids].clone()

    origins = env.scene.env_origins[env_ids]

    # use default pose as much as possible
    positions = root_states[:, :3].clone()
    orientations = root_states[:, 3:7].clone()

    # place around env origin
    positions[:, 0] = origins[:, 0] + root_states[:, 0]
    positions[:, 1] = origins[:, 1] + root_states[:, 1]
    positions[:, 2] = origins[:, 2] + 0.8

    # zero root velocity
    velocities = torch.zeros_like(root_states[:, 7:13])

    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)


def reset_root_state_paper_plot(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """
    Stable humanoid reset:
    - reset root pose to safe standing pose
    - reset root velocity to zero
    - reset joint positions/velocities to default
    """

    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    root_states = asset.data.default_root_state[env_ids].clone()
    origins = env.scene.env_origins[env_ids]

    # -----------------------------
    # 1) reset root pose
    # -----------------------------
    positions = root_states[:, :3].clone()
    orientations = root_states[:, 3:7].clone()

    positions[:, 0] = origins[:, 0]
    positions[:, 1] = origins[:, 1]
    positions[:, 2] = origins[:, 2] + 0.8

    velocities = torch.zeros_like(root_states[:, 7:13])

    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)

    # -----------------------------
    # 2) reset joints
    # -----------------------------
    if hasattr(asset.data, "default_joint_pos") and hasattr(asset.data, "default_joint_vel"):
        joint_pos = asset.data.default_joint_pos[env_ids].clone()
        joint_vel = torch.zeros_like(asset.data.default_joint_vel[env_ids])

        # 1) 写实际关节状态
        asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)

        # 2) 清 position / velocity / effort target
        if hasattr(asset, "set_joint_position_target"):
            asset.set_joint_position_target(joint_pos, env_ids=env_ids)
        if hasattr(asset, "set_joint_velocity_target"):
            asset.set_joint_velocity_target(joint_vel, env_ids=env_ids)
        if hasattr(asset, "set_joint_effort_target"):
            asset.set_joint_effort_target(torch.zeros_like(joint_pos), env_ids=env_ids)

        # 3) 再写一遍实际关节状态，覆盖可能的内部回写
        asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)
    if hasattr(env, "action_manager") and hasattr(env.action_manager, "reset"):
        try:
            env.action_manager.reset(env_ids=env_ids)
            print("[AUTO-RESET-DBG] action_manager.reset env_ids =", env_ids.detach().cpu().tolist(), flush=True)
        except TypeError:
            env.action_manager.reset(env_ids)
            print("[AUTO-RESET-DBG] action_manager.reset(done_ids) =", env_ids.detach().cpu().tolist(), flush=True)


###
# Planner Reset
###


def reset_robot_position_planner(
    env: ManagerBasedRLEnv,
    env_ids: torch.Tensor,
    yaw_range: tuple[float, float],
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
    goal_command_generator_name: str = "goal_command",
    spawn_in_env_frame: bool = False,
):
    """Reset the asset root state to the spawn state defined by the command generator.

    G1-safe version:
    - zero root velocity
    - slightly higher root z
    - slight crouch at reset for stability
    """
    asset: Articulation = env.scene[asset_cfg.name]

    if isinstance(env.command_manager.get_term(goal_command_generator_name), GoalCommand | FixGoalCommand):
        goal_cmd_generator: GoalCommand = env.command_manager.get_term(goal_command_generator_name)  # type: ignore
    elif isinstance(env.command_manager.get_term(goal_command_generator_name), MixedCommand):
        mixed_cmd_geneator: MixedCommand = env.command_manager.get_term(goal_command_generator_name)  # type: ignore
        goal_cmd_generator: GoalCommand = mixed_cmd_geneator.get_subterm("planner")  # type: ignore
    else:
        raise ValueError(f"Command type {type(env.command_manager._terms['command'])} not supported.")

    # ------------------------------------------------------------------
    # 1) Root position
    # ------------------------------------------------------------------
    positions = asset.data.default_root_state[env_ids, :3].clone()
    positions += goal_cmd_generator.pos_spawn_w[env_ids]

    origins = env.scene.env_origins[env_ids]
    if spawn_in_env_frame:
        positions[:, :2] += origins[:, :2]

    # More conservative z for humanoid reset
    positions[:, 2] = origins[:, 2] + 0.85

    # ------------------------------------------------------------------
    # 2) Root orientation
    # ------------------------------------------------------------------
    yaw_samples = sample_uniform(yaw_range[0], yaw_range[1], (len(env_ids), 1), device=asset.device)
    yaw_samples += goal_cmd_generator.heading_spawn_w[env_ids].unsqueeze(1)
    orientations = quat_from_euler_xyz(
        torch.zeros_like(yaw_samples),
        torch.zeros_like(yaw_samples),
        yaw_samples,
    ).squeeze(1)

    # ------------------------------------------------------------------
    # 3) Root velocity: force zero for humanoid reset stability
    # ------------------------------------------------------------------
    velocities = torch.zeros((len(env_ids), 6), device=asset.device)

    # write root state first
    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)

    # ------------------------------------------------------------------
    # 4) Joint state: default pose + slight crouch
    # ------------------------------------------------------------------
    default_joint_pos = asset.data.default_joint_pos[env_ids].clone()
    default_joint_vel = torch.zeros_like(asset.data.default_joint_vel[env_ids])

    # cache joint ids
    if not hasattr(asset, "_g1_reset_joint_ids"):
        hip_pitch_ids, _ = asset.find_joints(["left_hip_pitch_joint", "right_hip_pitch_joint"])
        knee_ids, _ = asset.find_joints(["left_knee_joint", "right_knee_joint"])
        ankle_pitch_ids, _ = asset.find_joints(["left_ankle_pitch_joint", "right_ankle_pitch_joint"])

        asset._g1_reset_joint_ids = {
            "hip_pitch_ids": hip_pitch_ids,
            "knee_ids": knee_ids,
            "ankle_pitch_ids": ankle_pitch_ids,
        }

        print("[RESET DBG] hip_pitch_ids =", hip_pitch_ids)
        print("[RESET DBG] knee_ids =", knee_ids)
        print("[RESET DBG] ankle_pitch_ids =", ankle_pitch_ids)

    hip_pitch_ids = asset._g1_reset_joint_ids["hip_pitch_ids"]
    knee_ids = asset._g1_reset_joint_ids["knee_ids"]
    ankle_pitch_ids = asset._g1_reset_joint_ids["ankle_pitch_ids"]

    # slight crouch for stability
    default_joint_pos[:, hip_pitch_ids] -= 0.15
    default_joint_pos[:, knee_ids] += 0.30
    default_joint_pos[:, ankle_pitch_ids] -= 0.15

    asset.write_joint_state_to_sim(default_joint_pos, default_joint_vel, env_ids=env_ids)